### ISSUE TITLE
Volume Profiles bugged despite uninstalled

### ISSUE THREAD

**Issue by Nova1ite** [notPlancha/volume-profiles-v2#4]
Some reason my volume profiles are still present even though it's uninstalled
I mean, I could do a clean uninstall where I remove Spicetify and Spotify files completely, but this is weird
Also, the buttons still work even uninstalled

<img width="1440" alt="Screenshot 2023-08-03 at 12 26 44 AM" src="https://github.com/notPlancha/volume-profiles-v2/assets/115776661/9da6e763-03b1-4654-85d5-03912bda0cf5">

**Comment by notPlancha** [comment]
I somewhat recently updated the extension so maybe the marketplace doesn't recognize it as it being the same extension

Check the installed tab (under More), and check if the extension is loaded on the config (`spicetify -c`)

**Comment by notPlancha** [comment]
Marking as stale
